#!/usr/bin/env sh

USERNAME="node-exporter"
TEXTFILE_WRITERS="node-exporter-textfile-writers"

addgroup \
    --system \
    $TEXTFILE_WRITERS

adduser \
    --system \
    --home /nonexistent \
    --no-create-home \
    --shell $(which nologin) \
    --disabled-login \
    --group \
    $USERNAME

usermod \
    --append \
    --groups $TEXTFILE_WRITERS \
    $USERNAME

systemctl daemon-reload
