#!/usr/bin/env sh

USERNAME="node-exporter"

adduser \
    --system \
    --home /nonexistent \
    --no-create-home \
    --shell $(which nologin) \
    --disabled-login \
    --group \
    $USERNAME

systemctl daemon-reload
